function [tseg_nii,deffwd_nii,aparc_nii,perirhinalR_nii,perirhinalL_nii,at_nii,pm_nii] = ...
	prep_files(inp)

% ROIs from container
copyfile(which('AT_Network_ROIs.nii.gz'), ...
	fullfile(inp.out_dir,'AT_Network_ROIs.nii.gz'));
gunzip(fullfile(inp.out_dir,'AT_Network_ROIs.nii.gz'));
delete(fullfile(inp.out_dir,'AT_Network_ROIs.nii.gz'));
at_nii = fullfile(inp.out_dir,'AT_Network_ROIs.nii');

copyfile(which('PM_Network_ROIs.nii.gz'), ...
	fullfile(inp.out_dir,'PM_Network_ROIs.nii.gz'));
gunzip(fullfile(inp.out_dir,'PM_Network_ROIs.nii.gz'));
delete(fullfile(inp.out_dir,'PM_Network_ROIs.nii.gz'));
pm_nii = fullfile(inp.out_dir,'PM_Network_ROIs.nii');

% MNI space deformation field
copyfile(inp.deffwd_niigz,[inp.out_dir '/y_deffwd.nii.gz']);
system(['gunzip -f ' inp.out_dir '/y_deffwd.nii.gz']);
deffwd_nii = [inp.out_dir '/y_deffwd.nii'];

% Temporal lobe
copyfile(inp.tseg_niigz,[inp.out_dir '/tseg.nii.gz']);
system(['gunzip -f ' inp.out_dir '/tseg.nii.gz']);
tseg_nii = [inp.out_dir '/tseg.nii'];

% Freesurfer - need to convert from surface label or mgz to nifti volume
system([ ...
	'FREESURFER_HOME=' inp.fs_dir ...
	'&& source $FREESURFER_HOME/FreeSurferEnv.sh && ' ...
	'mri_label2vol --identity ' ...
	'--label ' inp.subj_dir '/label/rh.perirhinal_exvivo.label ' ...
	'--temp ' inp.subj_dir '/mri/aparc.DKTatlas+aseg.mgz ' ...
	'--o ' inp.out_dir '/perirhinal-r.nii' ...
	]);
perirhinalR_nii = [inp.out_dir '/perirhinal-r.nii'];

system([ ...
	'FREESURFER_HOME=' inp.fs_dir ...
	'&& source $FREESURFER_HOME/FreeSurferEnv.sh && ' ...
	'mri_label2vol --identity ' ...
	'--label ' inp.subj_dir '/label/lh.perirhinal_exvivo.label ' ...
	'--temp ' inp.subj_dir '/mri/aparc.DKTatlas+aseg.mgz ' ...
	'--o ' inp.out_dir '/perirhinal-l.nii' ...
	]);
perirhinalL_nii = [inp.out_dir '/perirhinal-l.nii'];

system([ ...
	'FREESURFER_HOME=' inp.fs_dir ...
	'&& source $FREESURFER_HOME/FreeSurferEnv.sh && ' ...
	'mri_convert ' ...
	inp.subj_dir '/mri/aparc.DKTatlas+aseg.mgz ' ...
	inp.out_dir '/aparc.nii' ...
	]);
aparc_nii = [inp.out_dir '/aparc.nii'];
