function [deffwd_nii,aparc_nii] = ...
	prep_files(inp)

% MNI space deformation field
copyfile(inp.deffwd_niigz,[inp.out_dir '/y_deffwd.nii.gz']);
system(['gunzip -f ' inp.out_dir '/y_deffwd.nii.gz']);
deffwd_nii = [inp.out_dir '/y_deffwd.nii'];

% Freesurfer - need to convert from mgz to nifti volume
system([ ...
	'FREESURFER_HOME=' inp.fs_dir ' ' ...
	'&& source $FREESURFER_HOME/FreeSurferEnv.sh && ' ...
	'mri_convert ' ...
	inp.aparc_mgz ' ' ...
	inp.out_dir '/aparc.nii' ...
	]);
aparc_nii = [inp.out_dir '/aparc.nii'];
