function [deffwd_nii,aparc_nii,perirhinalR_nii,perirhinalL_nii] = ...
	prep_files(inp)

% MNI space deformation field
copyfile(inp.deffwd_niigz,[inp.out_dir '/y_deffwd.nii.gz']);
system(['gunzip -f ' inp.out_dir '/y_deffwd.nii.gz']);
deffwd_nii = [inp.out_dir '/y_deffwd.nii'];

% Freesurfer - need to convert from surface label or mgz to nifti volume
system([ ...
	'FREESURFER_HOME=' inp.fs_dir ...
	'&& source $FREESURFER_HOME/FreeSurferEnv.sh && ' ...
	'mri_label2vol --identity ' ...
	'--label ' inp.subj_dir '/label/rh.perirhinal_exvivo.label ' ...
	'--temp ' inp.subj_dir '/mri/aparc.DKTatlas+aseg.mgz ' ...
	'--o ' inp.out_dir '/perirhinal-r.nii' ...
	]);
perirhinalR_nii = [inp.out_dir '/perirhinal-r.nii'];

system([ ...
	'FREESURFER_HOME=' inp.fs_dir ...
	'&& source $FREESURFER_HOME/FreeSurferEnv.sh && ' ...
	'mri_label2vol --identity ' ...
	'--label ' inp.subj_dir '/label/lh.perirhinal_exvivo.label ' ...
	'--temp ' inp.subj_dir '/mri/aparc.DKTatlas+aseg.mgz ' ...
	'--o ' inp.out_dir '/perirhinal-l.nii' ...
	]);
perirhinalL_nii = [inp.out_dir '/perirhinal-l.nii'];

system([ ...
	'FREESURFER_HOME=' inp.fs_dir ...
	'&& source $FREESURFER_HOME/FreeSurferEnv.sh && ' ...
	'mri_convert ' ...
	inp.subj_dir '/mri/aparc.DKTatlas+aseg.mgz ' ...
	inp.out_dir '/aparc.nii' ...
	]);
aparc_nii = [inp.out_dir '/aparc.nii'];
