function rsrc_nii = reslice_images(src_nii,tgt_nii,interp)

flags = struct( ...
	'mask',true, ...
	'mean',false, ...
	'interp',interp, ...
	'which',1, ...
	'wrap',[0 0 0], ...
	'prefix','r');

spm_reslice({tgt_nii src_nii},flags);

[p,n,e] = fileparts(src_nii);
rsrc_nii = fullfile(p,['r' n e]);
